# Generated by Django 3.2.12 on 2022-12-01 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inn',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.RenameField(
            model_name='admin',
            old_name='login',
            new_name='hotelName',
        ),
        migrations.RenameField(
            model_name='admin',
            old_name='password',
            new_name='quantityFree',
        ),
        migrations.RenameField(
            model_name='manager',
            old_name='login',
            new_name='hotelName',
        ),
        migrations.RenameField(
            model_name='manager',
            old_name='password',
            new_name='tourop',
        ),
        migrations.RenameField(
            model_name='touroperator',
            old_name='login',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='touroperator',
            old_name='password',
            new_name='client',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default=0, max_length=6),
            preserve_default=False,
        ),
    ]
